# Generated by Django 3.0.4 on 2020-05-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('BREAK_FIX', 'Break/fix'), ('FEATURE', 'New feature'), ('OPTIMIZATION', 'Optimization')], default='BREAK_FIX', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATE', 'Investigate'), ('TRRIAGE', 'Await Approval'), ('BUILD_IN_PROGRESS', 'Build in progress'), ('VALIDATE', 'Validate'), ('COMPLETE', 'Complete'), ('CLOSED', 'Closed')], default='TODO', max_length=20),
        ),
    ]
    